[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/', 'forge-std/=lib/forge-std/src/']
eth-rpc-url = 'https://mainnet.infura.io/v3/9928b52099854248b3a096be07a6b23c'
fork_block_number = 144000000

# See more config options https://github.com/gakonst/foundry/tree/master/config